import Head from 'next/head';
import Header from '@/components/common/header/header';
import Hero from '@/components/Home/hero';
import HomeComparison from '@/components/Home/home_comparison';
import HomeTemplates from '@/components/Home/home_templates';
import HomeSports from '@/components/Home/home_sports';
import HomeFacilities from '@/components/Home/home_facilities';
import HomePricing from '@/components/Home/home_pricing';
import HomeTestimonial from '@/components/Home/home_testimonial';
import Footer from '@/components/common/footer/footer';
import { items } from '@/data/data';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Hero />
        <HomeComparison />
        <HomeTemplates items={items}/>
        <HomeSports />
        <HomeFacilities />
        <HomePricing />
        <HomeTestimonial />
        <Footer />
      </main>
    </>
  )
}
